name: nfcpay_structure
description: nfcpay_structure

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  get_storage: ^2.1.1
  logger: ^2.4.0
  pin_code_fields: 8.0.1
  intl: ^0.19.0
  image_picker: 1.1.2
  dotted_line: ^3.2.3
  flutter_svg: 2.0.12
  flutter_animate: ^4.5.0
  connectivity_plus: ^6.1.0
  patterns_canvas: ^0.5.0
  flutter_inappwebview: ^6.1.5
  r_dotted_line_border: ^0.1.1
  carousel_slider: ^5.0.0
  loading_animation_widget: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  video_player:
  flutter_custom_clippers: ^2.1.0
  flutter_card_swiper: ^7.0.2
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  camera: ^0.10.6
  cached_network_image: ^3.3.1
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  widget_to_marker: ^1.0.6
  sticky_headers: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
    - images/car.png
    - images/location.png
    - assets/icons/location.png